### ISSUE TITLE
rendering tick bug

### ISSUE THREAD

**Issue by msjavan** [os-js/osjs-widgets#3] opened 2020-01-29 19:31 UTC
In the [custom widget example](https://manual.os-js.org/v3/tutorial/widget/), fps event keep working, even after removing the widget, until the next desktop reload.

**Comment by andersevenrud** [comment] 2020-01-29 19:59
Looking at the code it seems like this is the case. The animator needs to have a condition to abort when widget destroy method is called.

**Comment by andersevenrud** [comment] 2020-01-29 22:04
Fix incoming: https://github.com/os-js/osjs-widgets/pull/4

**Comment by andersevenrud** [comment] 2020-01-29 22:08
I've just published `@osjs/widgets@3.0.2` that should fix this issue.

Let me know how it works out and close this issue :)

**Comment by msjavan** [comment] 2020-02-02 16:12
I cloned the "3.0.2" > run "npm install" > change the dependency in src/client/index.js   but still not solved for existing widgets.

**Comment by andersevenrud** [comment] 2020-02-02 16:33
Can you share this setup ?

Also, did you rebuild afterwards ?

I'm also interested in how you reproduce this error.

**Comment by msjavan** [comment] 2020-02-03 06:58
My mistake! I forget to change dependency in MyWidget.js too.
So I change it to: import {Widget} from '../osjs-widgets/index.js'; 
now got following error in the client side:

Uncaught TypeError: Class constructor Widget cannot be invoked without 'new'
    at new MyWidget (MyWidget.js:15)
    at Object.create (provider.js:82)
    at Object.onclick (provider.js:130)
    at Object.onclick [as click] (Menu.js:90)
    at HTMLDivElement.g (index.js:156)

you can see this by adding chart1 in my deployment

**Comment by andersevenrud** [comment] 2020-02-03 10:57
There's something wrong with your import statement most likely.

**Comment by andersevenrud** [comment] 2020-02-03 10:57
Also, you can just use the npm version -- you don't need to clone anything.

**Comment by msjavan** [comment] 2020-02-10 13:00
This problem still not solved, which one is correct for import:

import Widget from '../osjs-widgets/index.js';
or 
import {Widget} from '../osjs-widgets/index.js';


the former occurs following error:

TypeError: Super expression must either be null or a function inherits.js:5
    _inherits inherits.js:5
    MyWidget osjs.js:200
    js MyWidget.js:12
    Webpack 6
        __webpack_require__
        js
        __webpack_require__
        checkDeferredModules
        <anonymous>
        <anonymous>


but the latter occurs following error:

Uncaught TypeError: Class constructor Widget cannot be invoked without 'new'
at new MyWidget (MyWidget.js:15)
at Object.create (provider.js:82)
at Object.onclick (provider.js:130)
at Object.onclick [as click] (Menu.js:90)
at HTMLDivElement.g (index.js:156)

**Comment by andersevenrud** [comment] 2020-02-10 13:08
The correct usage with the official package is `import {Widget} from ...`.

If you maybe could share your files here https://gist.github.com/ ?

**Comment by msjavan** [comment] 2020-02-10 13:35
Here it is

https://gist.github.com/msjavan/c872f10687278f99b62c85723d7a9e2a

**Comment by andersevenrud** [comment] 2020-02-10 13:39
And the contents of `../osjs-widgets/index.js` is the actual osjs-widgets repo ?

**Comment by msjavan** [comment] 2020-02-10 13:40
import './index.scss';
import WidgetServiceProvider from './src/provider';
import Widget from './src/widget';
import DigitalClockWidget from './src/items/digitalclock';

export {
  WidgetServiceProvider,
  Widget,
  DigitalClockWidget
};

**Comment by andersevenrud** [comment] 2020-02-10 13:43
Looks OK. What happens if you remove the `index.js` part of the path so that it loads the pre-compiled version instead ?

**Comment by msjavan** [comment] 2020-02-10 13:50
Uncaught TypeError: Class constructor Widget cannot be invoked without 'new'
    at new MyWidget (MyWidget.js:15)
    at Object.create (provider.js:82)
    at Object.onclick (provider.js:130)
    at Object.onclick [as click] (Menu.js:90)
    at HTMLDivElement.g (index.js:156)

**Comment by andersevenrud** [comment] 2020-02-10 13:53
You have to do `import {Widget} from '../osjs-widgets';`

The curly braces **must be used** when `export` is create (and not `export default`) .

**Comment by msjavan** [comment] 2020-02-10 13:56
sorry, It already was {Widget}, I wrote it above by mistake.

**Comment by andersevenrud** [comment] 2020-02-10 13:57
Can you paste the latest error message and update the gist ? Because line numbers no longer match up.

**Comment by msjavan** [comment] 2020-02-10 13:59
I update the gist, It seems that its working !

**Comment by msjavan** [comment] 2020-02-10 14:00
I think the problem was I didn't rpm run build @ osjs-widget,  I did run "npm install" before

**Comment by msjavan** [comment] 2020-02-10 14:02
and "rendering tick bug" is resolved !

**Comment by andersevenrud** [comment] 2020-02-10 14:02
Great!

**Closed** 2020-02-10 14:05 UTC
Labels: bug
